dist: trusty
language: java
jdk:
- openjdk13

addons:
  sonarcloud:
    organization: "pierciro"
    token:
      secure: "114c84dfbc9f12f2f40017498e277ab9b91fca43"

script:
- ant build
- sonar-scanner